//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into {{table}} {{column}} values {{value}};.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from {{table}} where id = @id.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa thành công!.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu truyền lên không thỏa mãn.
        /// </summary>
        internal static string ErrClient {
            get {
                return ResourceManager.GetString("ErrClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        internal static string ErrData {
            get {
                return ResourceManager.GetString("ErrData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác!.
        /// </summary>
        internal static string errLogin {
            get {
                return ResourceManager.GetString("errLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đăng nhập không phải là chủ cửa hàng!.
        /// </summary>
        internal static string errNotExitShop {
            get {
                return ResourceManager.GetString("errNotExitShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi nội bộ!.
        /// </summary>
        internal static string ErrServer {
            get {
                return ResourceManager.GetString("ErrServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from {{table}} where id = @id.
        /// </summary>
        internal static string getDetail {
            get {
                return ResourceManager.GetString("getDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from {{table}} order by id desc limit 1.
        /// </summary>
        internal static string getIdMax {
            get {
                return ResourceManager.GetString("getIdMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from .
        /// </summary>
        internal static string getList {
            get {
                return ResourceManager.GetString("getList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from user where email = {{email}} and password = {{password}}.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from user where email = {{email}} and password = {{password}} and id_shop is not null.
        /// </summary>
        internal static string loginShop {
            get {
                return ResourceManager.GetString("loginShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công!.
        /// </summary>
        internal static string successLogin {
            get {
                return ResourceManager.GetString("successLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE {{table}} SET {{value}} where id={{id}}.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
    }
}
